routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::middleware('auth')
     ->prefix('admin')
     ->namespace('Admin')
     ->as('admin.')
     ->group(function () {

         //Route::get('/', 'AlbumController@index')->name('index');
         Route::resource('album', 'AlbumController');
         /*
          * Photo routes
          */
         Route::get('photo/create/{album}', 'PhotoController@create')
              ->name('photo.create');
         Route::post('photo/create/{album}', 'PhotoController@store')
              ->name('photo.store');
         Route::get('/photos/{photo}/edit', 'PhotoController@edit')
              ->name('photo.edit');
         Route::put('/photos/{photo}', 'PhotoController@update')
              ->name('photo.update');
         Route::delete('/photos/{photo}', 'PhotoController@destroy')
              ->name('photo.destroy');

         Route::middleware('ajax')
              ->group(function () {
                  Route::post('/ajax/order-album', 'OrderController@orderAlbum');
                  Route::post('/ajax/order-photo', 'OrderController@orderPhoto');
              });
     });

Route::get('/album/{album}', 'AlbumController@show')
     ->name('album.show');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('index');
Auth::routes();

app/Models/Album.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('order', 'asc')
                ->orderBy('created_at', 'desc');
        });

        static::deleting(function (Album $album) {
            foreach ($album->photos as $photo) {
                unlink(public_path('photos') . DIRECTORY_SEPARATOR . $photo->filename);
            }
            $album->photos()->delete();
        });
    }

    protected $fillable = [
        'title',
        'description',
        'order'
    ];

    protected $casts = [
        'created_at' => 'datetime:Y-m-d',
    ];

    protected $attributes = [
        'order' => 0
    ];

    /**
     * Album's photos
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    /**
     * Amount of photo in album
     *
     * @return int
     */
    public function getPhotoCountAttribute()
    {
        return $this->hasMany(Photo::class)->count();
    }

    /**
     * Get latest photo for album
     *
     * @return Model|\Illuminate\Database\Eloquent\Relations\HasMany|null|object
     */
    public function latestPhoto()
    {
        return $this->hasOne(Photo::class)
            ->orderBy('order')
            ->latest()
            ->withDefault(
                [
                    'filename' => 'noimage.png'
                ]
            );
    }
}

app/Http/Controllers/Admin/AlbumController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AlbumRequest;
use App\Models\Album;
use App\Services\AlbumService;

class AlbumController extends Controller
{
    /*
     * @var AlbumService $albumService
     */
    private $albumService;

    public function __construct(AlbumService $albumService)
    {
        $this->albumService = $albumService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums = Album::with('latestphoto')->get();
        return view('admin.album.index', [
            'albums' => $albums
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.album.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AlbumRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(AlbumRequest $request)
    {
        $album = $this->albumService->store($request);
        return redirect()->route('admin.album.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Album $album
     * @return \Illuminate\Http\Response
     */
    public function show(Album $album)
    {
        return view('admin.album.show', ['album' => $album]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Album $album
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Album $album)
    {
        return view('admin.album.edit', ['album' => $album]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param AlbumRequest $request
     * @param  \App\Models\Album $album
     * @return \Illuminate\Http\Response
     */
    public function update(AlbumRequest $request, Album $album)
    {
        $this->albumService->store($request, $album);
        return redirect()->route('admin.album.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Album $album
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Album $album)
    {
        try {
            $album->delete();
        } catch (\Exception $e) {
            return redirect()->route('admin.album.index')
                             ->withErrors($e->getMessage());
        }
        return redirect()->route('admin.album.index');
    }
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Album;
use Illuminate\Http\Request;

class AlbumController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Album $album
     * @return \Illuminate\Http\Response
     */
    public function show(Album $album)
    {
        $photos = $album->photos()
                        ->get();
        return view('album.show', [
            'album' => $album,
            'photos' => $photos,
        ]);
    }

}

resources/views/admin/album/create.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="py-2">
        Create album
    </h1>
    <div class="row py-2">
        <div class="col-12">
            <form method="POST" action="{{ route('admin.album.store') }}">
                <div class="form-group">
                    <label for="title">Album title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ old('title') }}" />
                </div>
                <div class="form-group">
                    <label for="description">Album description</label>
                    <textarea id="description" name="description" class="form-control" rows="5">
                        {{ old('description') }}
                    </textarea>
                </div>
                @csrf
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/album/edit.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="py-2">
        Edit album
    </h1>
    <div class="row py-2">
        <div class="col-12">
            <form method="POST" action="{{ route('admin.album.update', $album) }}">
                @method('PUT')
                <div class="form-group">
                    <label for="title">Album title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ old('title') ?? $album->title }}" />
                </div>
                <div class="form-group">
                    <label for="description">Album description</label>
                    <textarea id="description" name="description" class="form-control" rows="5">
                        {{ old('description') ?? $album->description }}
                    </textarea>
                </div>
                @csrf
                <button type="submit" class="btn btn-primary">Edit</button>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/album/index.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="py-2">
        Albums
    </h1>
    <div class="row py-2">
        <div class="col-12">
            <a href="{{ route('admin.album.create') }}" class="btn btn-success btn-lg">+ Add album</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 py-2 d-flex align-items-stretch">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Order</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Created At</th>
                    <th>Cover Image</th>
                    <th>Photos amount</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($albums as $album)
                    <tr>
                        <td class="align-middle text-center" style="width: 9em">
                            <div class="form-group">
                                {!! Form::select('order', range(0, $albums->count()), $album->order, ['class' => 'text-center album-order', 'data-album' => $album->id]) !!}
                            </div>
                        </td>
                        <td class="align-middle">
                            {{ $album->title }}
                        </td>
                        <td class="align-middle">
                            {{ $album->description }}
                        </td>

                        <td class="align-middle">
                            {{ $album->created_at }}
                        </td>
                        <td class="align-middle">
                            <img src="/photos/{{ $album->latestphoto->filename }}" class="img-thumbnail img-fluid"/>
                        </td>

                        <td class="align-middle text-center">
                            <span class="badge badge-primary badge-pill">{{ $album->photo_count }}</span>
                        </td>
                        <td class="align-middle text-center">
                            <a class="btn btn-success" href="{{ route('admin.album.edit', $album) }}">
                                Edit album
                            </a>
                        </td>
                        <td class="align-middle text-center">
                            <a class="btn btn-warning" href="{{ route('admin.album.show', $album) }}">
                                View/edit photos
                            </a>
                        </td>
                        <td class="align-middle text-center">
                            <a class="btn btn-danger"
                               onclick="event.preventDefault();if(confirm('Delete album???'))document.getElementById('album-destroy-{{ $album->id }}').submit();">
                                Delete album
                            </a>
                            <form action="{{ route('admin.album.destroy', $album) }}" method="post"
                                  id="album-destroy-{{ $album->id }}" class="hidden">
                                {!! method_field('delete') !!}
                                {!! csrf_field() !!}
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/admin/album/show.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="py-2">
        Album's title "{{ $album->title }}"
    </h1>
    <h3>
        {{ $album->description }}
    </h3>

    <div class="row py-2">
        <div class="col-12">
            <a href="{{ route('admin.photo.create', $album) }}" class="btn btn-success btn-lg">+ Upload new photo</a>
        </div>
    </div>

    <div class="row">
        @foreach($photos = $album->photos as $photo)
            <div class="col-md-3 py-2 d-flex align-items-stretch">
                <div class="card">
                    <img class="card-img-top" src="/photos/{{ $photo->filename }}" alt="{{ $photo->title }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ $photo->title }}</h5>
                    </div>
                    <div class="card-footer">
                        <p>Order:</p>
                        <div class="form-group">
                            {!! Form::select('order', range(0, $photos->count()), $photo->order, ['class' => 'text-center photo-order form-control', 'data-photo' => $photo->id]) !!}
                        </div>
                        <a class="btn btn-warning" href="{{ route('admin.photo.edit', $photo) }}">
                            Edit
                        </a>
                        <a class="btn btn-danger"
                           onclick="event.preventDefault();if(confirm('Delete photo???'))document.getElementById('photo-destroy-{{ $photo->id }}').submit();"
                           href="#">
                            Delete
                        </a>
                        <form action="{{ route('admin.photo.destroy', $photo) }}" method="post"
                              id="photo-destroy-{{ $photo->id }}" class="hidden">
                            {!! method_field('delete') !!}
                            {!! csrf_field() !!}
                        </form>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection