routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::middleware('auth')
     ->prefix('admin')
     ->namespace('Admin')
     ->as('admin.')
     ->group(function () {

         //Route::get('/', 'AlbumController@index')->name('index');
         Route::resource('album', 'AlbumController');
         /*
          * Photo routes
          */
         Route::get('photo/create/{album}', 'PhotoController@create')
              ->name('photo.create');
         Route::post('photo/create/{album}', 'PhotoController@store')
              ->name('photo.store');
         Route::get('/photos/{photo}/edit', 'PhotoController@edit')
              ->name('photo.edit');
         Route::put('/photos/{photo}', 'PhotoController@update')
              ->name('photo.update');
         Route::delete('/photos/{photo}', 'PhotoController@destroy')
              ->name('photo.destroy');

         Route::middleware('ajax')
              ->group(function () {
                  Route::post('/ajax/order-album', 'OrderController@orderAlbum');
                  Route::post('/ajax/order-photo', 'OrderController@orderPhoto');
              });
     });

Route::get('/album/{album}', 'AlbumController@show')
     ->name('album.show');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index')->name('index');
Auth::routes();

app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('order', 'asc')
                    ->orderBy('created_at', 'desc');
        });

        /*
         * Delete file before before model delete
         */
        static::deleting(function (Photo $photo) {
            unlink(public_path('photos') . DIRECTORY_SEPARATOR . $photo->filename);
        });
    }

    protected $fillable = [
        'title',
        'filename',
        'order',
        'album_id'
    ];

    /**
     * Album
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function album()
    {
        return $this->belongsTo(Album::class);
    }
}

app/Http/Controllers/Admin/PhotoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\PhotoRequest;
use App\Models\Album;
use App\Models\Photo;
use App\Services\PhotoService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PhotoController extends Controller
{
    private $photoService;

    public function __construct(PhotoService $photoService)
    {
        $this->photoService = $photoService;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Album $album
     * @return \Illuminate\Http\Response
     */
    public function create(Album $album)
    {
        return view('admin.photo.create', [

            'album' => $album
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PhotoRequest $request
     * @param Album $album
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(PhotoRequest $request, Album $album)
    {
        $this->photoService->create($request, $album);
        return redirect()->route('admin.album.show', $album);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Photo $photo
     * @return \Illuminate\Http\Response
     */
    public function show(Photo $photo)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Photo $photo
     * @return \Illuminate\Http\Response
     */
    public function edit(Photo $photo)
    {
        return view('admin.photo.edit', [
            'photo' => $photo
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Photo $photo
     * @return \Illuminate\Http\Response
     */
    public function update(PhotoRequest $request, Photo $photo)
    {
        $this->photoService->update($request, $photo);
        return redirect()->route('admin.album.show', $photo->album);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Photo $photo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Photo $photo)
    {
        try {
            $photo->delete();
        } catch (\Exception $e) {
            return redirect()->route('admin.album.show', $photo->album)
                             ->withErrors($e->getMessage());
        }
        return redirect()->route('admin.album.show', $photo->album);
    }
}

resources/views/admin/photo/create.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="py-2">
        Photo upload to album "{{ $album->title }}"
    </h1>
    <div class="row py-2">
        <div class="col-12">
            <form method="POST" action="{{ route('admin.photo.store', $album) }}" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="title">Photo title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ old('title') }}"/>
                </div>
                <div class="form-group">
                    <label for="description">File</label>
                    <input type="file" name="filename" class="form-control-file"/>
                </div>
                @csrf
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>

@endsection

resources/views/admin/photo/edit.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="py-2">
        Edit photo
    </h1>
    <div class="row py-2">
        <div class="col-12">
            <form method="POST" action="{{ route('admin.photo.update', $photo) }}" enctype="multipart/form-data">
                @method('PUT')
                <div class="form-group">
                    <label for="title">Photo title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ old('title') ?? $photo->title }}"/>
                </div>
                <div class="form-group">
                    <label for="description">File (live empty for old file)</label>
                    <input type="file" name="filename" class="form-control-file" value="{{ old('filename') }}"/>
                </div>
                @csrf
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>

@endsection